### ISSUE TITLE
Uncaught TypeError: buffer.getHistory is not a function

### ISSUE THREAD

**Issue by snopy2015** [guiguan/file-header#48]
[Enter steps to reproduce below:]

1. Install file-header 
2. try to save any new file

The the error is popping up

Thanks for a response....

**Atom Version**: 1.8.0
**System**: Debian GNU/Linux
**Thrown From**: [file-header](https://github.com/guiguan/file-header) package, v1.13.5

### Stack Trace

Uncaught TypeError: buffer.getHistory is not a function

```
At /usr/share/atom/resources/app.asar/src/pane.js:1002

TypeError: buffer.getHistory is not a function
    at Object.module.exports.FileHeader.update (/home/yves/.atom/packages/file-header/lib/file-header.coffee:299:22)
    at /home/yves/.atom/packages/file-header/lib/file-header.coffee:164:10
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at TextBuffer.module.exports.TextBuffer.saveAs (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1091:20)
    at TextBuffer.module.exports.TextBuffer.save (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1083:19)
    at TextEditor.module.exports.TextEditor.save (/usr/share/atom/resources/app.asar/src/text-editor.js:660:26)
    at Pane.module.exports.Pane.saveItem (/usr/share/atom/resources/app.asar/src/pane.js:718:18)
    at Pane.module.exports.Pane.saveActiveItem (/usr/share/atom/resources/app.asar/src/pane.js:701:19)
    at Workspace.module.exports.Workspace.saveActivePaneItem (/usr/share/atom/resources/app.asar/src/workspace.js:684:35)
    at atom-workspace.commandRegistry.add.core:save (/usr/share/atom/resources/app.asar/src/register-default-commands.js:214:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:260:29)
    at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/usr/share/atom/resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/usr/share/atom/resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -1:34.8.0 window:save-all (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -1:21.7.0 file-header:add (atom-text-editor.editor.is-focused)
  4x -0:57.3.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "metrics",
      "markdown-preview",
      "autocomplete-ansible"
    ],
    "themes": [
      "one-dark-ui",
      "cobalt2-syntax"
    ]
  },
  "file-header": {
    "autoUpdateEnabled": true,
    "dateTimeFormat": "\"dddd, MMMM Do YYYY, h:mm:ss a\"",
    "enableFilename": true,
  }
}
```

### Installed Packages

```coffee
# User
ansible-vault, v0.6.7
atom-beautify, v0.30.5
cobalt2-syntax, v0.4.0
file-header, v1.13.5
language-ansible, v0.2.1
linter, v1.11.18
markdown-image-paste, v2.5.2
markdown-preview-plus, v2.4.0
markdown-table-editor, v0.6.4
markdown-themeable-pdf, v1.2.0
pdf-view, v0.59.0
prompt-big-file, v0.4.0
svn, v0.0.13
tool-bar-markdown-writer, v0.3.0

# Dev
No dev packages
```

**Comment by guiguan** [comment]
Can you try with the latest version of `Atom`?

**Comment by BenSokol** [comment]
I am getting presumably the same error. When I try saving any file, it shows:
'filename' could not be saved.
Error: undefined
This is with any file. If I disable File Header, everything works normally. This started after updating a few days ago. Im running Atom Stable (1.21.0).

**Comment by snopy2015** [comment]
Hi , I got the recommendation to use a newer version of Atom.io.

I am running Debian 8.9 . 
3.16.0-4-amd64 #1 SMP Debian 3.16.43-2+deb8u5 (2017-09-19) x86_64 GNU/Linux

I used the steps described in:
https://github.com/alanfranz/atom-text-editor-repository/blob/master/README.md

Now with Atom.IO version 1.21.0, the previous error is not popping up again. ... But the file header **_cannot be inserted in existing Atom.io project files_**. Only new files allow it. Strange 

Please comment if necessary.
